#ifndef MC_MCENV_H
#define MC_MCENV_H

#define ENV_MAX_DEPTH_PER_THREAD   "MCMINI_MAX_DEPTH_PER_THREAD"
#define ENV_DEBUG_AT_TRACE_ID      "MCMINI_DEBUG_AT_TRACE_ID"
#define ENV_PRINT_AT_TRACE_ID      "MCMINI_PRINT_AT_TRACE_ID"
#define ENV_FIRST_DEADLOCK         "MCMINI_FIRST_DEADLOCK"
#define ENV_CHECK_FORWARD_PROGRESS "MCMINI_CHECK_FORWARD_PROGRESS"
#define ENV_LONG_TEST              "MCMINI_LONG_TEST"
#define ENV_VERBOSE                "MCMINI_VERBOSE"

#endif // MC_MCENV_H
