#ifndef INCLUDE_MCMINI_TRANSITIONS_WRAPPERS_MCSEMAPHORETRANSITIONWRAPPERS_HPP
#define INCLUDE_MCMINI_TRANSITIONS_WRAPPERS_MCSEMAPHORETRANSITIONWRAPPERS_HPP

#include "mcmini/MCShared.h"
#include <semaphore.h>

MC_EXTERN int mc_sem_init(sem_t *, int, unsigned int);
MC_EXTERN int mc_sem_post(sem_t *);
MC_EXTERN int mc_sem_wait(sem_t *);

#endif // INCLUDE_MCMINI_TRANSITIONS_WRAPPERS_MCSEMAPHORETRANSITIONWRAPPERS_HPP
