#ifndef MC_MCENV_H
#define MC_MCENV_H

#define ENV_MAX_TRANSITIONS_DEPTH_LIMIT   "MCMINI_MAX_TRANSITIONS_DEPTH_LIMIT"
#define ENV_MAX_DEPTH_PER_THREAD          "MCMINI_MAX_DEPTH_PER_THREAD"
#define ENV_MAX_NO_PROGRESS               "MCMINI_MAX_NO_PROGRESS"
#define ENV_DEBUG_AT_TRACE_ID             "MCMINI_DEBUG_AT_TRACE_ID"
#define ENV_PRINT_AT_TRACE_ID             "MCMINI_PRINT_AT_TRACE_ID"
#define ENV_PRINT_AT_TRACE_SEQ            "MCMINI_PRINT_AT_TRACE_SEQ"
#define ENV_FIRST_DEADLOCK                "MCMINI_FIRST_DEADLOCK"
#define ENV_CHECK_FOR_LIVELOCK            "MCMINI_CHECK_FOR_LIVELOCK"
#define ENV_CHECK_FOR_WEAK_LIVELOCK       "MCMINI_CHECK_FOR_WEAK_LIVELOCK"
#define ENV_MAX_LIVELOCK_CYCLE_LIMIT      "MCMINI_MAX_LIVELOCK_CYCLE_LIMIT"
#define ENV_CHECK_FORWARD_PROGRESS        "MCMINI_CHECK_FORWARD_PROGRESS"
#define ENV_LONG_TEST                     "MCMINI_LONG_TEST"
#define ENV_QUIET                         "MCMINI_QUIET"
#define ENV_VERBOSE                       "MCMINI_VERBOSE"

#endif // MC_MCENV_H
